=== dostert01/ediconv/tests/testdata/pricatSchema02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!-- Root element -->
  <xs:element name="EdifactMessage">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="Segment" type="SegmentType" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element name="SegmentGroup" type="SegmentGroupType" maxOccurs="unbounded" minOccurs="0"/>
      </xs:choice>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="version" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- Segment definition -->
  <xs:complexType name="SegmentType">
    <xs:sequence>
      <xs:element name="Element" type="ElementType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="required" type="xs:boolean" use="required"/>
    <xs:attribute name="description" type="xs:string"/>
    <xs:attribute name="maxOccurs" type="xs:string" default="1"/>
  </xs:complexType>

  <!-- Element definition -->
  <xs:complexType name="ElementType">
    <xs:sequence>
      <xs:element name="Composite" type="CompositeType" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="position" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="required" type="xs:boolean" use="required"/>
    <xs:attribute name="description" type="xs:string" use="optional"/>
    <xs:attribute name="CodeListName" type="xs:string" use="optional"/>
    <xs:attribute name="CodeListAgency" type="xs:string" use="optional"/>
    <xs:attribute name="isQualifier" type="xs:boolean" use="optional"/>
  </xs:complexType>

  <!-- Composite definition -->
  <xs:complexType name="CompositeType">
    <xs:sequence>
      <xs:element name="Component" type="ComponentType" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
  </xs:complexType>

  <!-- Component definition -->
  <xs:complexType name="ComponentType">
    <xs:attribute name="position" type="xs:positiveInteger" use="required"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="required" type="xs:boolean" use="required"/>
    <xs:attribute name="CodeListName" type="xs:string" use="optional"/>
    <xs:attribute name="CodeListAgency" type="xs:string" use="optional"/>
    <xs:attribute name="isQualifier" type="xs:boolean" use="optional"/>
  </xs:complexType>

  <!-- Segment Group definition -->
  <xs:complexType name="SegmentGroupType">
    <xs:sequence>
      <xs:element name="Segment" type="SegmentType" maxOccurs="unbounded" minOccurs="1"/>
      <xs:element name="SegmentGroup" type="SegmentGroupType" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="start" type="xs:string" use="required"/>
    <xs:attribute name="repeat" type="xs:string" use="optional"/>
    <xs:attribute name="description" type="xs:string" use="optional"/>
    <xs:attribute name="maxOccurs" type="xs:string" use="optional"/>
  </xs:complexType>

</xs:schema>

=== dostert01/ediconv/tests/testdata/pricatSchema02.xml
<EdifactMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="pricatSchema02.xsd" type="PRICAT" version="D96A">

  <!-- Message Header -->
  <Segment name="UNH" required="true" description="Message header" maxOccurs="1">
    <Element position="1" name="Message Reference Number" required="true" />
    <Element position="2" name="Message Identifier" required="true" description="S009 Composite">
      <Composite name="S009 - Message Identifier">
        <Component position="1" name="Message Type" required="true" CodeListName="EDIFACT Message Types" CodeListAgency="UNECE" isQualifier="true" />
        <Component position="2" name="Message Version Number" required="true" />
        <Component position="3" name="Message Release Number" required="true" />
        <Component position="4" name="Controlling Agency" required="true" CodeListName="Controlling Agency Codes" CodeListAgency="UNECE" isQualifier="true" />
        <Component position="5" name="Association Assigned Code" required="false" />
      </Composite>
    </Element>
  </Segment>

  <!-- Beginning of message -->
  <Segment name="BGM" required="true" description="Beginning of message" maxOccurs="1">
    <Element position="1" name="Document Message Name" required="true" description="C002 Composite">
      <Composite name="C002 - Document_Message Name">
        <Component position="1" name="Document Name Code" required="true" CodeListName="Document_Message Name Codes" CodeListAgency="UNECE" isQualifier="true" />
        <Component position="2" name="Code List Responsible Agency" required="false" />
        <Component position="3" name="Document Name" required="false" />
      </Composite>
    </Element>
    <Element position="2" name="Document Message Number" required="true" />
    <Element position="3" name="Message Function Code" required="false" CodeListName="Message Function Codes" CodeListAgency="UNECE" isQualifier="true" />
  </Segment>

  <!-- Date_time_period -->
  <Segment name="DTM" required="true" description="Date_time_period" maxOccurs="35">
    <Element position="1" name="Date_Time_Period" required="true" description="C507 Composite">
      <Composite name="C507 - Date_Time_Period">
        <Component position="1" name="Date_Time_Period Qualifier" required="true" CodeListName="Date_Time_Period Qualifiers" CodeListAgency="UNECE" isQualifier="true" />
        <Component position="2" name="Date_Time_Period" required="true" />
        <Component position="3" name="Format Qualifier" required="false" CodeListName="Date_Time_Period Format Codes" CodeListAgency="UNECE" isQualifier="true" />
      </Composite>
    </Element>
  </Segment>

  <!-- Segment Group 1: Parties -->
  <SegmentGroup name="SG1_Parties" start="NAD" repeat="10" description="Name and address group" maxOccurs="10">
    <Segment name="NAD" required="true" description="Name and address" maxOccurs="1">
      <Element position="1" name="Party Function Code Qualifier" required="true" CodeListName="Party Function Codes" CodeListAgency="UNECE" isQualifier="true" />
      <Element position="2" name="Party Identification Details" required="true" description="C082 Composite">
        <Composite name="C082 - Party Identification Details">
          <Component position="1" name="Party Id" required="true" />
          <Component position="2" name="Code List Qualifier" required="false" CodeListName="Party Identification Code Lists" CodeListAgency="UNECE" isQualifier="true" />
          <Component position="3" name="Code List Responsible Agency Code" required="false" />
        </Composite>
      </Element>
      <Element position="3" name="Name and Address" required="false" />
      <Element position="4" name="Party Name" required="false" />
    </Segment>
  </SegmentGroup>

  <!-- Segment Group 22: Product Line Item -->
  <SegmentGroup name="SG22_ProductLineItem" start="LIN" repeat="9999" description="Product line item group" maxOccurs="9999">
    <Segment name="LIN" required="true" description="Line item" maxOccurs="1">
      <Element position="1" name="Line Item Number" required="true" />
      <Element position="2" name="Action Request Code" required="false" CodeListName="Action Request Codes" CodeListAgency="UNECE" isQualifier="true" />
      <Element position="3" name="Item Number Identification" required="true" description="C212 Composite">
        <Composite name="C212 - Item Number Identification">
          <Component position="1" name="Item Number" required="true" />
          <Component position="2" name="Code List Qualifier" required="false" CodeListName="Product Identification Code List" CodeListAgency="GS1" isQualifier="true" />
          <Component position="3" name="Code List Responsible Agency Code" required="false" />
        </Composite>
      </Element>
    </Segment>

    <!-- Segment Group 23: Additional product IDs -->
    <SegmentGroup name="SG23_ProductIDs" start="PIA" repeat="10" description="Additional product identification" maxOccurs="10">
      <Segment name="PIA" required="false" description="Additional product ID" maxOccurs="1">
        <Element position="1" name="Product ID Function Code" required="true" CodeListName="Product ID Function Codes" CodeListAgency="UNECE" isQualifier="true" />
        <Element position="2" name="Item Identification" required="true" description="C212 Composite">
          <Composite name="C212 - Item Number Identification">
            <Component position="1" name="Item Number" required="true" />
            <Component position="2" name="Code List Qualifier" required="false" CodeListName="Product Identification Code List" CodeListAgency="GS1" isQualifier="true" />
            <Component position="3" name="Code List Responsible Agency Code" required="false" />
          </Composite>
        </Element>
      </Segment>
    </SegmentGroup>

    <!-- Segment Group 25: Item Description -->
    <SegmentGroup name="SG25_ItemDescription" start="IMD" repeat="5" description="Item description" maxOccurs="5">
      <Segment name="IMD" required="false" description="Item description" maxOccurs="1">
        <Element position="1" name="Description Format Code" required="false" CodeListName="Description Format Codes" CodeListAgency="UNECE" isQualifier="true" />
        <Element position="2" name="Item Characteristic" required="false" />
        <Element position="3" name="Item Description" required="true" />
      </Segment>
    </SegmentGroup>

    <!-- Segment Group 27: Price Information -->
    <SegmentGroup name="SG27_PriceInformation" start="PRI" repeat="5" description="Price details" maxOccurs="5">
      <Segment name="PRI" required="false" description="Price details" maxOccurs="1">
        <Element position="1" name="Price Code Qualifier" required="true" CodeListName="Price Code Qualifiers" CodeListAgency="UNECE" isQualifier="true" />
        <Element position="2" name="Price Amount" required="true" />
        <Element position="3" name="Price Type Code" required="false" CodeListName="Price Type Codes" CodeListAgency="UNECE" isQualifier="true" />
        <Element position="4" name="Currency Code" required="false" CodeListName="Currency Codes" CodeListAgency="ISO 4217" isQualifier="true" />
      </Segment>
    </SegmentGroup>

    <!-- Segment Group 29: Quantity Information -->
    <SegmentGroup name="SG29_Quantity" start="QTY" repeat="10" description="Quantity information" maxOccurs="10">
      <Segment name="QTY" required="false" description="Quantity" maxOccurs="1">
        <Element position="1" name="Quantity Qualifier" required="true" CodeListName="Quantity Qualifiers" CodeListAgency="UNECE" isQualifier="true" />
        <Element position="2" name="Quantity" required="true" />
      </Segment>
    </SegmentGroup>

  </SegmentGroup>

  <!-- Message Trailer -->
  <Segment name="UNT" required="true" description="Message trailer" maxOccurs="1">
    <Element position="1" name="Segment Count" required="true" />
    <Element position="2" name="Message Reference Number" required="true" />
  </Segment>

</EdifactMessage>
